### ISSUE TITLE
Source tarball contains out-dated setup.py

### ISSUE THREAD

**Issue by fabaff** [Voyz/databay#8] opened 2020-09-04 11:25 UTC
**Describe the bug**
Creating a RPM packages from the 0.1.5 produces .egg-info that uses the previous version (0.1.4).

**To Reproduce**
1. Download source
2. Extract source
3. `cat databay-0.1.5/setup.py | grep version ` -> `version = '0.1.4',`

**Expected behavior**
Be able to create the needed content with the current release number.

**Environment**
Databay version: 0.1.5
Python version: Python 3.8.5
OS: Fedora 32/Rawhide

**Suggest a Fix**
Tag the source after all files are pushed to the repo. Publish a new release 0.1.6 as PyPI doesn't allow the re-upload of an existing release source tarball.

**Comment by Voyz** [comment] 2020-09-05 07:23
Thank you for reporting @fabaff 😄! I can confirm that this indeed is the case. I admit that my release process was faulty and caused this discrepancy. This is the first time I release open source, so do apologise for little slips like this one early on. Could you help me understand the release process that doesn't have this problem?

From what I understood ([following this tutorial][1]), the release happens in the following form:

1. Complete the code for the release, commit and push to `master`.
1. Create a release on GitHub
1. Copy the link to the Source code's tar.gz from the releases page
1. Paste that link into `setup.py` under `download_url`
1. Bump the `version` in `setup.py` to the same of the new release
1. Run `python setup.py sdist` and `twine upload dist/NEW_RELEASE.tar.gz`
1. Commit and push the updated `setup.py` and the `dist/NEW_RELEASE.tar.gz` to `master`

I understand your suggestion to move point `5.` to point `1.` - to bump the version code before creating a release on GitHub. However, then the `setup.py` would still contain the old `download_url`. Should I change the `download_url` in anticipation of the new release too, before it is even made?

As you can see, I'm slightly confused about the correct way, so appreciate your help in the matter!

[1]: https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56

**Comment by Voyz** [comment] 2020-09-15 02:59
After exploring a few dead ends, I've managed to find a number of sources reasoning that `download_url` is no longer needed, which I think should solve this issue. Sources:

https://stackoverflow.com/a/19759746/3508719
https://medium.com/@mail.fabian.keller/download-urlis-actually-no-longer-recommended-dabff66f2c90
https://github.com/pypa/packaging.python.org/issues/293

Will update accordingly for the next release. Thanks for participating!

**Comment by fabaff** [comment] 2020-09-25 19:32
Creating a release manually on GitHub seems to be like adding a tag. In your listing would you adjust the version in `setup.py` after the source is published on GitHub.

I usually do:

- `git tag -a 0.9.0 && git push origin 0.9.0`
- `python3 setup.py sdist upload` (or with `twine`)
- set the version in the `setup.py` to the next release or mark it as `dev`

after finished all open tasks. 

Could you please release 0.1.6? Would allow me to build the Fedora package without patching. Thanks.

**Comment by Voyz** [comment] 2020-09-28 02:48
Thanks for the info @fabaff. We had more fixes planned for 0.1.6 that are currently being implemented, but I can understand your request. I'll push 0.1.6 up just to fix this, should be out this week. Sorry for the wait and thanks for baring with us!

**Comment by Voyz** [comment] 2020-09-29 08:59
@fabaff I just released 0.1.6 as requested. Please give it a shot when you can and let me know if the issue is solved. Thank you for your help with this issue 😊

**Comment by Voyz** [comment] 2020-10-04 05:38
Closing this issue as we've verified the version discrepancy described is no longer present in 0.1.6. Please reopen if the issue persists. Thanks for reporting 🙂

**Closed by Voyz** 2020-10-04 05:38 UTC
Labels: bug
